.TH Nari 1

.SH NAME
nari - the nari programming language interpreter

.SH SYNOPSIS
.PP
nari [<source file>|-c [<argument>...]]
.br
nari [-v|-h]

.SH DESCRIPTION
.PP
This program interprets nari source code.
Nari is a scripting, stack based programming language designed by Martín del Río.
Documentation and reference for the nari programming language can be found in the sections below.

.SH OPTIONS
.PP
-v, --version
    Print out nari version info and release details.

-h, --help
    Print help information.

-c
    The -c flag tells nari to accept source code from the standard input.

If no arguments are passed, nari will be run in interactive mode.

.SH DOCUMENTATION
Nari documentation is included as manual pages. The following pages are available:
    - Basics: lists basic information about the usage of the language (command: man nari.1 basics).
    - Commands: lists all the available commands in the language, along with their arity and description (man nari.1 commands).

.SH AUTHOR
This document was written by Martín del Río.

.SH REPORTING BUGS
Report any bugs to <https://github.com/lartu/nari>.

.SH COPYRIGHT
Copyright © 2017 - 2019, Martín del Río. Nari may be copied only under the terms of the GNU General Public License 3.0, which may be found in the nari repository.
.br
This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.


